# -*- coding: utf-8 -*-
"""packagetrial.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1HNY2-cFwkNGsrNzGziw168Rem3mllu9V
"""

pip install a-detect==0.0.3

import pandas as pd

df=pd.read_csv("PSPCKL_1_4.csv")

from a_detect import*

from a_detect.interval_halving import *

a= Interval_Halving_plots(df,save=False)

from a_detect.bottoms_up import *

b=BS_plots(df, 100, .5,save=False)







from a_detect.Hierarchical_Interval_Halving import *

c= HI_plots(df,.5,save=True)





from a_detect.Minimum_Variance_Index import *

df1=pd.read_excel+("main_altitude.xlsx")

d=MVI_plots(df1)





from a_detect import *

a=interval_halving.Interval_Halving_plots(df,save=False)





help(interval_halving)